### ISSUE TITLE
Feature-Request: Compatibility ai_seo_helper with georgringer/news

### ISSUE THREAD

**Issue by elliehaupt** [passionweb-manuel-schnabel/ai-seo-helper#10]
I am requesting compatibility between the ai_seo_helper and georgringer/news extension. Currently, the ai_seo_helper extension does not have the capability to retrieve page content for news articles. 

This enhancement would enable efficient management of metadata, effective SEO optimization, and improved visibility for news articles. Thank you for considering this extension enhancement.

**Comment by passionweb-manuel-schnabel** [comment]
Hey @elliehaupt,

thank you for your feature request.

I agree with you that this feature would be very useful.

I'll try to get a first version compatible with georgringer/news as soon as possible.

This feature is certainly also interesting for e.g. t3g/blog or other similar extensions that are often used.

As soon as there is something new, you will hear from me.

Greetings Manu

**Comment by passionweb-manuel-schnabel** [comment]
Hey @elliehaupt,

I've just released version 0.6.0 which, among other things, has also added compatibility with EXT:news. Currently, the fields "description", "keywords" and "alternative_title" can be generated.

I would be happy if you would test the current approach and give me your feedback.

Greetings Manu

**Comment by elliehaupt** [comment]
Hello @passionweb-manuel-schnabel!

Apologies for the delay in getting back to you. Thank you for promptly implementing the changes I requested. After a brief review, it seems to be exactly what I had in mind. I'll conduct more thorough testing and provide detailed feedback if needed.

Thanks again for your hard work!

Best regards,
Ellie

**Comment by passionweb-manuel-schnabel** [comment]
@elliehaupt Thanks for the feedback! If anything needs to be adjusted, please let me know.

Greetings Manu
