### ISSUE TITLE
Unexpected error [object Object] on root page.

### ISSUE THREAD

**Issue by Pravin0711** [passionweb-manuel-schnabel/ai-seo-helper#11]
Hello @passionweb-manuel-schnabel 

I am using typo3 version 11.5 and ai_seo_helper version 0.6.1. All thing work fine with all sub pages. i face issue on root page. it's work fine with defult language. But on other languages i will get error `Unexpected error [object Object].`

I have debug your code and seen `site` is not founded(get `NULL` value) for other langages in class `ContentService.php line 225`. I think it's happening due to take rootPageID 0.

Please check it and provide your feedback.

**Comment by passionweb-manuel-schnabel** [comment]
Hi @Pravin0711 
thx for your bug report. 
This is really an interesting behaviour. I've also analysed this and commit a fix for that. It would be great if you update the extension to the main branch and test the fix. Would love to hear from you again if this fix works.
Greetings 
Manu

**Comment by Pravin0711** [comment]
Hello @passionweb-manuel-schnabel 

Thanks for quick update ans fix it. Yes it's working fine now with another languages.

One more Question: some time i get `resulted in a `404 Not Found` response:`  is there i missing any extension configuration?

**Comment by ManuS3009** [comment]
Hi,

sometimes the preview content cannot be created because of a trailing slash (e.g. on translated root pages). But I have now inserted a fallback for this.

In addition, the page must always be active, otherwise the preview content generation will not work

**Comment by passionweb-manuel-schnabel** [comment]
Hi,

sometimes the preview content cannot be created because of a trailing slash (e.g. on translated root pages). But I have now inserted a fallback for this.

In addition, the page must always be active, otherwise the preview content generation will not work

I will close this issue with the next release 0.6.2.
