### ISSUE TITLE
Disturbing comment in <head> in frontend

### ISSUE THREAD

**Issue by wowaTYPO3** [passionweb-manuel-schnabel/ai-seo-helper#6]
In the frontend source code of a page where the extension was used, a large comment in the form of the following appears in the <head> area:

/*<![CDATA[*/
--
  | var TYPO3 = Object.assign(TYPO3 \|\| {}, Object.fromEntries(Object.entries({"lang":{"AiSeoHelper.generation.keywords

etc. etc.

This can be seen here, for example: https://wwagner.net/typo3-workshops-schulungen

**Comment by passionweb-manuel-schnabel** [comment]
Hey Wolfgang,

I took a look at the problem and moved the integration of the inline language file into an event that is only fired in the backend.

The problem should now be fixed with the new version 0.5.1 and no additional script should be added within the head tag in the frontend.
